Change regex

diff --git a/.github/workflows/branch-name-validation.yml b/.github/workflows/branch-name-validation.yml
--- a/.github/workflows/branch-name-validation.yml
+++ b/.github/workflows/branch-name-validation.yml
@@ -20,8 +20,6 @@ jobs:
           echo "Validating branch name: $BRANCH_NAME"
 
           # Add your regex here, same you use in validate-branch-name package
-          REGEX="^(main){1}$|^(chore|hotfix)\\/([\w\-\d]+)$|^(\w+\-\d+)\/([\w\-\d]+)$|^(dependabot-npm_and_yarn-[\\w\\-\\d\\.]+)$"
-          if ! [[ "$BRANCH_NAME" =~ $REGEX ]]; then
-            echo "::error title=Invalid branch name::Branch name '$BRANCH_NAME' does not match the required pattern."
-            exit 1
+          REGEX="^(main)$|^(chore|hotfix)/([\w-]+)$|^(\w+-\d+)/([\w-]+)$|^(dependabot-npm_and_yarn-[\w.-]+)$"
+          if ! [[ "$BRANCH_NAME" =~ $REGEX ]]; then echo "::error title=Invalid branch name::Branch name '$BRANCH_NAME' does not match the required pattern. Pattern: $REGEX" exit 1
           fi
